In [1]:
import numpy as np

In [2]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

### Implement mean Absolute error

In [3]:
def mean_abs_err(y_predicted, y_true):
    total_error = 0
    for y_pred, y_true in zip(y_predicted, y_true):
        total_error += abs(y_pred-y_true)
    print('Total error is :', total_error)
    mean_abs_err = total_error/len(y_predicted)
    print('Mean absolute error is:', mean_abs_err)
    return mean_abs_err
        

In [4]:
mean_abs_err(y_predicted, y_true)

Total error is : 2.5
Mean absolute error is: 0.5


0.5

### Implement same thing using numpy array

In [21]:
np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [6]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [7]:
def mae(y_predicted, y_true):
    y = np.mean(np.abs(y_predicted - y_true))
    return y
    

In [8]:
mae(y_predicted, y_true)

0.5

### Implement log loss or Binary Cross Entropy

In [9]:
np.log([0])

C:\Users\Yash Kumar\anaconda4\envs\py3-TF1\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([-inf])

In [23]:
epsilon = 1e-15

In [24]:
np.log([1e-15])

array([-34.53877639])

In [25]:
y_predicted

array([1, 1, 0, 0, 1])

In [26]:
y_predicted_new = [max(i, epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [27]:
1 - epsilon

0.999999999999999

In [28]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [29]:
y_predicted_new = np.array(y_predicted_new)
y_predicted_new

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])

In [30]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [31]:
-np.mean(y_true*np.log(y_predicted_new) + (1-y_true)*np.log(1 - y_predicted_new))

17.2696280766844

In [32]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return   -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [33]:
log_loss(y_true, y_predicted)

17.2696280766844

### Mean Squared Error

In [35]:
## Without using numpy array
def mse(y_predicted, y_true):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += (yp - yt)**2
    print('Total Squared Error:', total_error)
    mse = total_error/len(y_true)
    print('Mean Squared Error :', mse)
    return mse
    

In [36]:
mse(y_predicted, y_true)

Total Squared Error: 1.83
Mean Squared Error : 0.366


0.366

In [37]:
### By using numpy array
np.mean(np.square(y_true - y_predicted))

0.366